### ISSUE TITLE
Add summaries for resources

### ISSUE THREAD

**Issue by ravenclaw1999** [DiversityCorp/companies-on-blm#241] opened 2020-12-27 22:09 UTC
#### Issue Description
Currently there are no summaries for the resources on the resources page. If anyone wants to either add a short description to the resources already on the page or provide additional resources to add, that would be awesome :)

**Comment by aditya28sarin** [comment] 2020-12-29 05:32
Can you assign this issue to me?

**Comment by ravenclaw1999** [comment] 2020-12-29 05:50
It's all yours!

**Comment by aditya28sarin** [comment] 2020-12-29 19:53
I have added all the summaries on the resources page. Kindly let me know if I have added as it was intended to.
It is a great project to work on!

**Comment by ravenclaw1999** [comment] 2020-12-29 20:40
Thank you so much! I will look over your PR :)

**Closed** 2021-03-28 18:48 UTC
Labels: content
